apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: KubePrometheusStack
metadata:
  name: kube-prometheus-stack
  namespace: example-env
spec:
  clusterName: example-cluster
  namespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        remoteWrite:
          - url: http://mimir-distributor.monitoring:8080/api/v1/push
            headers:
              X-Scope-OrgID: example-cluster
